### ISSUE TITLE
Use existing subtitles option is not working

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aws-solutions/content-localization-on-aws#11]
We switched from using dropzone to Amplify for file uploads when we merged with MIE 2.0.  The Amplify component is a single file upload.  We rely on being able to upload multiple files for uploading the side-car subtitles with the input video for analysis.

Custom labels prob won't work on media-insights project as well due to this.

**Comment by julianklotz** [comment]
Hey there! While looking for documentation on the “use existing subtitles” option, I only found this ticket and wonder how it works. There’s a filed for entering a file name, but nothing else (no upload option). I’m currently testing a public HTTP URL to my existing files, but not sure whether this works. Is there any documentation or can you provide any background?

This option would be quite important to us, hoping that it can dramatically improve the quality of translations.
