### ISSUE TITLE
Add python safety scan to automated PR tests

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aws-solutions/content-localization-on-aws#156]
Unpinned requirements will generate a warning by python `safety`.
```
pip3 install safety
safety check -r aws-media-insights-content-localization/test/e2e/requirements.txt
```

_Originally posted by @ianwow in https://github.com/aws-samples/aws-media-insights-content-localization/pull/154#discussion_r703915700_

**Comment by ianwow** [comment]
Dependabot performs the same checks as python `safety`. So, I think this issue has become obsolete.
