### ISSUE TITLE
Rename Subtitle to Captions and Translation to Subtitle to Match HTML Spec

### ISSUE THREAD

**Issue by jasonoma-aws** [aws-solutions/content-localization-on-aws#273]
**Is your feature request related to a problem? Please describe.**
Currently within the UI source language VTT and SRT files are labeled as "subtitles" and translated files are labeled as "translations":
<img width="1435" alt="Screen Shot 2021-12-09 at 6 16 02 PM" src="https://user-images.githubusercontent.com/95241370/146249313-c40b0caa-22ee-46fb-8f74-4fdd9ea86df0.png">

This differs from the definition described in the [HTML spec for track elements](https://html.spec.whatwg.org/multipage/media.html#the-track-element):

_Captions | Transcription or translation of the dialogue, sound effects,  relevant musical cues, and other relevant audio information, suitable  for when sound is unavailable or not clearly audible (e.g. because it is  muted, drowned-out by ambient noise, or because the user is deaf).  Overlaid on the video; labeled as appropriate for the  hard-of-hearing._

_Subtitles | Transcription or translation of the dialogue, suitable for when  the sound is available but not understood (e.g. because the user does  not understand the language of the media resource's audio track). Overlaid on the video._

This definition also aligns with other definitions on the internet: 
Ex: [Rev.com](https://www.rev.com/blog/subtitles-vs-captions) [Vimeo](https://vimeo.com/blog/post/the-difference-between-subtitles-and-captions/) [3Play](https://www.3playmedia.com/blog/captions-vs-subtitles-do-you-know-the-difference/) [Accredited Language & Services](https://www.accreditedlanguage.com/subtitles-captions/subtitles-and-captions-whats-the-difference/)

Although this definition can vary from [service](https://captionmax.com/wp-content/uploads/2021/11/Captionmax-Captions-vs-Subtitles.pdf) to [service](https://www.fcc.gov/consumers/guides/closed-captioning-television) and region to region. 

**Describe the feature you'd like**
**Rename:** Subtitles -> Captions or Captions (Original Language)
**Rename:** Translations -> Subtitles or Subtitles (Translations)

**Additional context**
From my experience, the definitions of captions and subtitles is fluid so this is just a suggestion based on my past experience with captions and subtitles in media and entertainment. 

I am writing a blog post to describe how to use this solution and wanted to raise this before it gets published to make sure my description is accurate.

**Comment by raulmlamzn** [comment]
@jasonoma-aws We've carefully considered your feedback and have decided not to include this feature in a future release of this solution.
