### ISSUE TITLE
Dataplane error on ios devices

### ISSUE THREAD

**Issue by solminkim** [aws-solutions/content-localization-on-aws#355]
**Describe the bug**

I got "Dataplane error. Please check browser and dataplane logs" message when I open the Content localization webpage on iPad and iPhone (not in android mobile device). Also when I upload video file and start workflow, got same error message and workflow did not started.

When I see log with safari user-agent changed with IOS 16 iPhone below logs are shown:

"Failed to load resource: Origin https://cloudfrontid.cloudfront.net is not allowed by Access-Control-Allow-Origin. Status code: 403",

"XMLHttpRequest cannot load https://apigatewayid.execute-api.us-east-1.amazonaws.com/api/download due to access control checks"

**To Reproduce**

Open Content localization webpage with iPad or iPhone. The error message will show in main collection page. 

**Expected behavior**

Error message did not appear and workflow starts well.

**Please complete the following information about the solution:**

- [x] Version: v1.0.0

- [x] Region: us-east-1

- [x] Was the solution modified from the version published on this repository? No

- [x] If the answer to the previous question was yes, are the changes available on GitHub?

- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes

- [x] Were there any errors in the CloudWatch Logs? No

**Screenshots**
![clo-dataplane-error](https://user-images.githubusercontent.com/91516514/210703018-66ea5ac5-03aa-450c-b7ed-3426182d677c.png)

![image](https://user-images.githubusercontent.com/91516514/210706228-54f8e720-7695-408d-a512-fc66409f4c03.png)

**Additional context**

**Comment by cassneal** [comment]
@solminkim thanks for filing this issue. We have added it our backlog to look into further.

**Comment by eggoynes** [comment]
@solminkim Are you still seeing this issue? Can you try deploying the newest V2.1.1 of the solution, and let us know if that fixes your issue. Thank you. 

https://aws.amazon.com/solutions/implementations/content-localization-on-aws/
