### ISSUE TITLE
Separate subtitle edit "save" and "trigger workflow" buttons -> prevent editing freeze for 60+ minutes

### ISSUE THREAD

**Issue by bquast** [aws-solutions/content-localization-on-aws#357]
Saving edits to subtitles automatically triggers a new workflow, freezing the editing mode for e.g. 60+ minutes for a typical 1-hour video.

This can be inconvenient because:

1. Editors often notice final fixes just after saving.
2. Editors want to save their changes frequently in order to prevent any loss of their progress

It would be helpful to separate the "save" button, for saving the edits, from the "trigger workflow" button.

**Comment by bquast** [comment]
What also might be useful a "workflow running" indicator, so that you can at least know when you cannot make edits

**Comment by cassneal** [comment]
Thank you for filing this enhancement request. We have added this to our backlog to review.

**Comment by raulmlamzn** [comment]
@bquast Thanks for submitting the feedback. We've carefully considered your feedback and have decided not to include this  feature in a future release of this solution.
