### ISSUE TITLE
Ability to specifify metadata when uploading a new video

### ISSUE THREAD

**Issue by louishourcade** [aws-solutions/content-localization-on-aws#370]
**Is your feature request related to a problem? Please describe.**

With the current solution, users can configure the workflow when uploading a video. The workflow then analyses the content of the video to generate metadata.
It would be helpful for customers to be able to **define metadata when uploading the video as well**. An example would be a manufacturing customer willing to create media hub for its maintenance videos. In this case, users would need to specify some metadata (such as plant_id, plant_location, ...) when uploading an asset.
Contrary to the way the solution currently works, these metadata cannot be extracted from the video itself, hence the requirement for a mechanism to handle user-defined metadata.

**Describe the feature you'd like**

* When uploading a new video, users can associate key/value tags to the asset.
* These tags are stored in the dataplane (DynamoDB and Opensearch)
* Users can browse assets based on the metadata they specified when uploading the video
* Users can edit/delete key/value tags associated to the video at any time

**Comment by raulmlamzn** [comment]
@louishourcade Thanks for submitting the feedback. We decided we will not add the functionality to this solution.
