### ISSUE TITLE
Deployment in Private Subnets

### ISSUE THREAD

**Issue by louishourcade** [aws-solutions/content-localization-on-aws#371]
**Is your feature request related to a problem? Please describe.**

The current solution deploys resources in public subnets of the default VPC. This does not satisfy security and networking requirements for most customers.

**Describe the feature you'd like**

When deploying the stack, there could be a parameter to decide whether the deployment happens in public subnets or private subnets:
* **Public**: No change to the current deployment
* **Private**: The stack creates a new VPC wit public and private subnets (or use an existing VPC stack). Backend resources (Lambda, Opensearch, ...) are then deployed within the private subnets. The stack also deploys VPC endpoints to enable communication with AWS services outside of the VPC.

**Comment by cassneal** [comment]
This has been added to our backlog for this solution. We will comment here if this gets prioritized for a release. Thank you.

**Comment by cassneal** [comment]
Thank you for your suggestion.  We've carefully considered your feedback and have decided not to include this feature in a future release.
