### ISSUE TITLE
Upload failed if I switched to the Collection view while videos were being processed

### ISSUE THREAD

**Issue by jkbredsquiggles** [aws-solutions/content-localization-on-aws#391]
**Describe the bug**

I started an upload of two videos. After the workflow started, I switched to the Collections view to work with some already completed videos. When I went back to the "upload" view, it was empty. The videos didn't show up in the collection.

As with my other bug report. This was the first time I used the project, so there may be user error.

**To Reproduce**

1. Upload a few videos. I don't think it matters, but accept the default parameters and add a French Canadian translation. (this populates the collection)
2. When completed, Upload a few more with the same workflow configuration.
3. While processing, click on the collections tab. Do some stuff
4. Go back to the "Upload" tab.
5. Videos are gone and there is no history.

**Expected behavior**

Videos would show up in the collection and the history would show the results/status of the video processing.

**Please complete the following information about the solution:**

- [SO0164 ] 

- [us-east-1]

- [No ] Was the solution modified from the version published on this repository?

- [ N/A] If the answer to the previous question was yes, are the changes available on GitHub?

- [ No] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?

- [Unknown ] Were there any errors in the CloudWatch Logs?

**Screenshots**

Sorry, no screen shots.

**Additional context**

None that I can think of.

**Comment by raulmlamzn** [comment]
@jkbredsquiggles Did you check the "Execution History" section at the bottom of the Upload page (below the "Configure Workflow" section)? You might need to scroll down to see it in your browser. Once you upload content and run a workflow, this section will display the status of the workflow, if it started, completed or reported any errors. You can open the status and check the details of the step functions involved in the AWS console.

**Comment by raulmlamzn** [comment]
Closing this issue since we didn't hear back from the user. Feel free to re-open with more details.
